[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [{name = "Jérome Eertmans", email = "jeertmans@icloud.com"}]
dependencies = [
  "pulsectl>=23.5.2",
  "pycaw>=20240210;os_name=='nt'",
  "pydantic>=2.1.1;os_name=='posix'",
  "pyside6>=6.5.2",
  "rtoml>=0.11.0",
  "rich>=13.7.1"
]
description = "Jingle Box for Tournaments"
license = "MIT"
name = "jinglebox"
readme = "README.md"
repository = "https://github.com/jeertmans/jinglebox"
requires-python = ">=3.9"
version = "0.1.0"

[project.scripts]
jinglebox = "jinglebox.__main__:main"

[tool.rye]
dev-dependencies = [
  "pre-commit>=3.5.0",
  "pyinstaller>=6.10.0"
]
managed = true
